/* Copyright (c) Jeremy Webb. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet AESMS MT3620 Starter Kit to the
// abstraction used for the peripherals for the Safe Sound project.

// This file is autogenerated from ../../safe_sound_hardware.json.  Do not edit it directly.

#pragma once
#include "avnet_aesms_mt3620.h"

// AVNET AESMS MT3620: Button A.
#define BUTTON_A AVNET_AESMS_PIN14_GPIO12

// AVNET AESMS MT3620: Button A.
#define BUTTON_B AVNET_AESMS_PIN15_GPIO13

// AVNET AESMS MT3620: Red LED.
#define LED_RED AVNET_AESMS_PIN11_GPIO8

// AVNET AESMS MT3620: Green LED.
#define LED_GREEN AVNET_AESMS_PIN12_GPIO9

// AVNET AESMS MT3620: Blue LED.
#define LED_BLUE AVNET_AESMS_PIN13_GPIO10

// AVNET AESMS MT3620: ADC Microphone controller
#define MICROPHONE_CONTROLLER AVNET_AESMS_ADC_CONTROLLER0

// AVNET AESMS MT3620: Connect external microphone ADC controller 0, channel 1 using SOCKET1 AN.
#define MICROPHONE AVNET_AESMS_ADC_CHANNEL1

